# Generated by Django 4.2.10 on 2024-03-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companyemployee',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='companyemployee',
            unique_together={('company', 'email')},
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='username',
        ),
    ]
