# Generated by Django 4.2.10 on 2024-03-19 06:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0003_alter_companyemployee_company'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companyemployee',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='companyemployee',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='role',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
