# Generated by Django 4.2.10 on 2024-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0004_alter_companyemployee_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyemployee',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
