# Generated by Django 4.2.10 on 2024-03-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0005_alter_companyemployee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
