# Generated by Django 4.2.10 on 2024-03-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0006_alter_companyemployee_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployee',
            name='username',
            field=models.CharField(default='Employee', max_length=150),
        ),
    ]
