# Generated by Django 4.2.10 on 2024-03-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0008_alter_companyemployee_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyemployee',
            options={},
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='username',
        ),
    ]
