# Generated by Django 4.2.10 on 2024-03-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0009_alter_companyemployee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
