# Generated by Django 4.2.10 on 2024-03-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0010_companyemployee_is_active_companyemployee_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyEmployee',
        ),
    ]
